version: "3.8"
services:
  rtmp:
    image: alfg/nginx-rtmp
    container_name: rtmp-server
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/opt/data/hls
      - ./webroot:/www/static
